const projects = [
	{
		id: 1,
		title: "Maestra Patagónica",
		subtitle: "Tienda de Recursos Educativos",
		description: "Plataforma e-commerce especializada en recursos educativos para docentes. Incluye sistema de compras, catálogo interactivo y área de usuario.",
		technologies: ["HTML5","React", "Node.js", "MongoDB", "Vite", "Tailwind CSS"],
		category: "ecommerce",
		github: "https://github.com/31pablo05/MaestraPatagonica",
		demo: "https://maestra-patagonica.vercel.app/inicio",
		videoSrc: "/videosProjects/MaestraPatagonica.mp4",
		posterSrc: "/posters/posterMaestraPatagonica.PNG",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Proyecto completado y en producción activa",
		progress: 20,
		icon: "GraduationCap",
		startDate: "2024-01",
		endDate: "2024-03",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 2,
		title: "SPA Chacra Pichirayen",
		subtitle: "Sitio Web de Spa y Bienestar",
		description: "Sitio web elegante para spa con sistema de reservas, galería de servicios y información detallada de tratamientos.",
		technologies: ["HTML5", "Tailwind CSS", "JavaScript", "React", "Vite"],
		category: "wellness",
		github: "https://github.com/31pablo05/PichiRayen/tree/main",
		demo: "https://pichi-rayen-swpt.vercel.app/",
		videoSrc: "/videosProjects/PichiRayen.mp4",
		posterSrc: "/posters/posterPichiRayen.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Sitio web activo con todas las funcionalidades",
		progress: 100,
		icon: "Heart",
		startDate: "2024-02",
		endDate: "2024-04",
		clientType: "Bienestar",
		teamSize: 1
	},
	{
		id: 3,
		title: "Web App Nutricionista",
		subtitle: "Aplicación de Nutrición",
		description: "Aplicación web para consultorio nutricional con calculadoras de IMC, planes alimentarios y gestión de pacientes.",
		technologies: ["HTML5", "Css", "React", "Tailwind CSS", "JavaScript", "Vite"],
		category: "health",
		github: "https://github.com/31pablo05/NutricionistaPamelaWeissberg",
		demo: "https://nutricionista-pamela-weissberg.vercel.app/",
		videoSrc: "/videosProjects/WebAppNutricionista.mp4",
		posterSrc: "/posters/posterNutricionista.PNG",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Aplicación completa y funcionando",
		progress: 90,
		icon: "Utensils",
		startDate: "2024-01",
		endDate: "2024-02",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 4,
		title: "Web App Prepizzas",
		subtitle: "Sistema de Pedidos de Pizzería",
		description: "Sistema de pedidos online para pizzería con menú interactivo, carrito de compras y seguimiento de pedidos en tiempo real.",
		technologies: ["HTML5","React", "Node.js", "JavaScript", "Render", "Tailwind CSS","vite"],
		category: "food",
		github: "https://github.com/31pablo05/Prepizzas/tree/main",
		demo: "https://prepizzas.vercel.app/",
		videoSrc: "/videosProjects/WebAppPrepizzas.mp4",
		posterSrc: "/posters/posterAppPrepizzas.PNG",
		featured: false,
		status: "Producción",
		detailedStatus: "En fase de testing y optimización",
		progress: 100,
		icon: "Utensils",
		startDate: "2024-04",
		endDate: "2024-06",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 5,
		title: "Federico Fotografía y Video",
		subtitle: "Portfolio Creativo",
		description: "Portfolio profesional para fotógrafo y videomaker con galería dinámica, efectos visuales y formulario de contacto.",
		technologies: ["HTML5","CSS","React", "JavaScript", "Vite", "Tailwind CSS", "Framer Motion"],
		category: "portfolio",
		github: "https://github.com/31pablo05/FedeForquera/tree/main/Fede.Forquera.Photographer-Filmmaker",
		demo: "https://fede-forquera-photographer-filmmake.vercel.app/",
		videoSrc: "/videosProjects/FedeForquera.mp4",
		posterSrc: "/posters/posterFilmaker.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Portfolio activo con galería completa",
		progress: 100,
		icon: "Camera",
		startDate: "2024-03",
		endDate: "2024-05",
		clientType: "Creativo",
		teamSize: 1
	},
	{
		id: 6,
		title: "Web App Osteopatía",
		subtitle: "Aplicación Médica",
		description: "Plataforma para consultorio de osteopatía con sistema de turnos, historial de pacientes y información de tratamientos.",
		technologies: ["HTML5", "CSS", "React", "Tailwind CSS", "JavaScript", "Vite"],
		category: "health",
		github: "https://github.com/31pablo05/appFranciscoTorres",
		demo: "https://app-francisco-torres.vercel.app/",
		videoSrc: "/videosProjects/FranciscoTorresOsteopatia.mp4",
		posterSrc: "/posters/posterOsteopatia.PNG",
		featured: false,
		status: "Producción",
		detailedStatus: "Implementando sistema de turnos",
		progress: 100,
		icon: "Heart",
		startDate: "2024-05",
		endDate: "2024-07",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 7,
		title: "Aplicación de Escritorio - Tareas Diarias",
		subtitle: "App de Productividad",
		description: "Aplicación de escritorio para gestión de tareas diarias con drag & drop, notificaciones y análisis de rendimiento.",
		technologies: ["Electron", "React", "JavaScript", "Tailwind CSS", "CSS"],
		category: "productivity",
		github: "#",
		demo: "#",
		videoSrc: "#",
		posterSrc: "/posters/TaDi-Captura.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Desarrollando funciones avanzadas",
		progress: 60,
		icon: "Code2",
		startDate: "2024-04",
		endDate: "2024-08",
		clientType: "Productividad",
		teamSize: 1
	},
	{
		id: 8,
		title: "Web App Convertidor de Videos a MP3",
		subtitle: "Herramienta de Conversión",
		description: "Aplicación web para convertir videos a formato MP3 con interfaz intuitiva, progreso en tiempo real y descarga directa.",
		technologies: ["React", "FFmpeg.js", "Web Workers", "File API", "Tailwind CSS"],
		category: "tools",
		github: "#",
		demo: "#",
		videoSrc: "",
		posterSrc: "https://picsum.photos/800/600?random=8",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Herramienta completamente funcional",
		progress: 100,
		icon: "Music",
		startDate: "2024-02",
		endDate: "2024-03",
		clientType: "Herramientas",
		teamSize: 1
	},
	{
		id: 9,
		title: "MYBEAUTYSTUDY",
		subtitle: "Tratamientos de Cejas y Pestañas",
		description: "Plataforma web para estudio de belleza especializado en cejas y pestañas. Incluye sistema de reservas, catálogo de servicios y área de contacto profesional.",
		technologies: ["HTML5", "CSS", "React", "JavaScript", "Tailwind CSS", "Vite"],
		category: "beauty",
		github: "https://github.com/31pablo05/MYBeautyStudy",
		demo: "https://my-beauty-study.vercel.app/",
		videoSrc: "/videosProjects/MyBeautyStudy.mp4",
		posterSrc: "/posters/posterMYBEAUTYSTUDY.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Estudio activo con sistema de reservas y catálogo completo",
		progress: 100,
		icon: "Sparkle",
		startDate: "2025-05",
		endDate: "2025-06",
		clientType: "Belleza",
		teamSize: 1
	},
	{
		id: 10,
		title: "Micropigmentadora Internacional",
		subtitle: "Certificación Internacional en Micropigmentación",
		description: "Landing page para profesional internacional, promocionando curso certificado en micropigmentación. Incluye información detallada, formulario de inscripción y testimonios.",
		technologies: ["HTML5", "CSS", "React", "JSX", "JavaScript", "Tailwind CSS", "Vite"],
		category: "beauty",
		github: "https://github.com/31pablo05/-micropicmentadoraInternacional-/tree/main/curso-flavia",
		demo: "https://micropicmentadora-internacional.vercel.app/",
		videoSrc: "/videosProjects/MicropigmentadoraLanding.mp4",
		posterSrc: "/posters/posterMicropigmentadora.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Landing activa para venta de curso internacional",
		progress: 100,
		icon: "Certificate",
		startDate: "2025-04",
		endDate: "2025-05",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 11,
		title: "CafeDoncar",
		subtitle: "Especialistas en Pizzas y Hamburguesas 100% Caseras",
		description: "Web SPA para restaurante con menú online, sistema de armado de pedido y envío directo por WhatsApp. Incluye galería de productos y promociones.",
		technologies: ["HTML5", "CSS", "React", "JSX","JavaScript", "Tailwind CSS", "WhatsApp API"],
		category: "food",
		github: "https://github.com/31pablo05/CafeDoncar",
		demo: "https://cafe-doncar.vercel.app/",
		videoSrc: "/videosProjects/CafeDoncar.mp4",
		posterSrc: "/posters/posterCafeDoncar.PNG",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Sistema de pedidos online funcionando",
		progress: 70,
		icon: "Pizza",
		startDate: "2025-05",
		endDate: "",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 12,
		title: "OZZcycling",
		subtitle: "Bicicletería y Taller Especializado",
		description: "Web institucional para bicicletería premium en Buenos Aires. Presenta servicios de taller, catálogo de productos y centro Shimano Service Center Oficial.",
		technologies: ["HTML5", "CSS", "React", "JSX","JavaScript", "Tailwind CSS", "Vite", "WhatsApp API"],
		category: "retail",
		github: "https://github.com/31pablo05/OZZcycling",
		demo: "https://ozzcycling.vercel.app/",
		videoSrc: "/videosProjects/OZZcycling.mp4",
		posterSrc: "/posters/posterOZZ.PNG",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Sitio web activo y actualizado",
		progress: 70,
		icon: "Bike",
		startDate: "2025-07",
		endDate: "",
		clientType: "Retail",
		teamSize: 2
	}
];

export default projects;
