const projects = [
	{
		id: 1,
		title: "Maestra Patagónica",
		subtitle: "Tienda de Recursos Educativos",
		description: "Plataforma e-commerce especializada en recursos educativos para docentes. Incluye sistema de compras, catálogo interactivo y área de usuario.",
		technologies: ["React", "Node.js", "MongoDB", "Stripe", "Tailwind CSS"],
		category: "ecommerce",
		github: "#",
		demo: "#",
		videoSrc: "/videosProjects/maestra-patagonica.mp4",
		posterSrc: "https://picsum.photos/800/600?random=1",
		featured: true,
		status: "Producción",
		detailedStatus: "Proyecto completado y en producción activa",
		progress: 100,
		icon: "GraduationCap",
		startDate: "2024-01",
		endDate: "2024-03",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 2,
		title: "SPA Chacra Pichirayen",
		subtitle: "Sitio Web de Spa y Bienestar",
		description: "Sitio web elegante para spa con sistema de reservas, galería de servicios y información detallada de tratamientos.",
		technologies: ["HTML5", "Tailwind CSS", "JavaScript", "React", "Vite"],
		category: "wellness",
		github: "https://github.com/31pablo05/PichiRayen",
		demo: "https://pichi-rayen-swpt.vercel.app/",
		videoSrc: "/videosProjects/VIDEOSPA.mp4",
		posterSrc: "/images webp/Pichi-Rayencaptura.webp",
		featured: true,
		status: "Producción",
		detailedStatus: "Sitio web activo con todas las funcionalidades",
		progress: 100,
		icon: "Heart",
		startDate: "2024-02",
		endDate: "2024-04",
		clientType: "Bienestar",
		teamSize: 1
	},
	{
		id: 3,
		title: "Web App Nutricionista",
		subtitle: "Aplicación de Nutrición",
		description: "Aplicación web para consultorio nutricional con calculadoras de IMC, planes alimentarios y gestión de pacientes.",
		technologies: ["HTML5", "React", "Tailwind CSS", "JavaScript", "Chart.js"],
		category: "health",
		github: "https://github.com/31pablo05/PamelaWeissberg",
		demo: "https://pamela-weissberg.vercel.app/",
		videoSrc: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
		posterSrc: "https://picsum.photos/800/600?random=3",
		featured: true,
		status: "Producción",
		detailedStatus: "Aplicación completa y funcionando",
		progress: 100,
		icon: "Utensils",
		startDate: "2024-01",
		endDate: "2024-02",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 4,
		title: "Web App Prepizzas",
		subtitle: "Sistema de Pedidos de Pizzería",
		description: "Sistema de pedidos online para pizzería con menú interactivo, carrito de compras y seguimiento de pedidos en tiempo real.",
		technologies: ["React", "Node.js", "Socket.io", "MongoDB", "Express"],
		category: "food",
		github: "#",
		demo: "#",
		videoSrc: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
		posterSrc: "https://picsum.photos/800/600?random=4",
		featured: false,
		status: "Desarrollo",
		detailedStatus: "En fase de testing y optimización",
		progress: 85,
		icon: "Utensils",
		startDate: "2024-04",
		endDate: "2024-06",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 5,
		title: "Federico Fotografía y Video",
		subtitle: "Portfolio Creativo",
		description: "Portfolio profesional para fotógrafo y videomaker con galería dinámica, efectos visuales y formulario de contacto.",
		technologies: ["React", "GSAP", "Lightbox", "Tailwind CSS", "Framer Motion"],
		category: "portfolio",
		github: "#",
		demo: "#",
		videoSrc: "/videosProjects/FedeForquera.mp4",
		posterSrc: "/posters/posterFilmaker.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Portfolio activo con galería completa",
		progress: 100,
		icon: "Camera",
		startDate: "2024-03",
		endDate: "2024-05",
		clientType: "Creativo",
		teamSize: 1
	},
	{
		id: 6,
		title: "Web App Osteopatía",
		subtitle: "Aplicación Médica",
		description: "Plataforma para consultorio de osteopatía con sistema de turnos, historial de pacientes y información de tratamientos.",
		technologies: ["Vue.js", "Express", "MySQL", "Calendar API", "Node.js"],
		category: "health",
		github: "#",
		demo: "#",
		videoSrc: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
		posterSrc: "https://picsum.photos/800/600?random=6",
		featured: false,
		status: "Desarrollo",
		detailedStatus: "Implementando sistema de turnos",
		progress: 70,
		icon: "Heart",
		startDate: "2024-05",
		endDate: "2024-07",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 7,
		title: "Aplicación de Escritorio - Tareas Diarias",
		subtitle: "App de Productividad",
		description: "Aplicación de escritorio para gestión de tareas diarias con drag & drop, notificaciones y análisis de rendimiento.",
		technologies: ["Electron", "React", "TypeScript", "SQLite", "Node.js"],
		category: "productivity",
		github: "#",
		demo: "#",
		videoSrc: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
		posterSrc: "https://picsum.photos/800/600?random=7",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Desarrollando funciones avanzadas",
		progress: 60,
		icon: "Code2",
		startDate: "2024-04",
		endDate: "2024-08",
		clientType: "Productividad",
		teamSize: 1
	},
	{
		id: 8,
		title: "Web App Convertidor de Videos a MP3",
		subtitle: "Herramienta de Conversión",
		description: "Aplicación web para convertir videos a formato MP3 con interfaz intuitiva, progreso en tiempo real y descarga directa.",
		technologies: ["React", "FFmpeg.js", "Web Workers", "File API", "Tailwind CSS"],
		category: "tools",
		github: "#",
		demo: "#",
		videoSrc: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
		posterSrc: "https://picsum.photos/800/600?random=8",
		featured: true,
		status: "Producción",
		detailedStatus: "Herramienta completamente funcional",
		progress: 100,
		icon: "Music",
		startDate: "2024-02",
		endDate: "2024-03",
		clientType: "Herramientas",
		teamSize: 1
	},
	{
		id: 9,
		title: "MYBEAUTYSTUDY",
		subtitle: "Tratamientos de Cejas y Pestañas",
		description: "Plataforma web para estudio de belleza especializado en cejas y pestañas. Incluye sistema de reservas, catálogo de servicios y área de contacto profesional.",
		technologies: ["React", "Tailwind CSS", "Vite", "EmailJS"],
		category: "beauty",
		github: "#",
		demo: "#",
		videoSrc: "/videosProjects/MYBeautyStudy.mp4",
		posterSrc: "https://picsum.photos/800/600?random=9",
		featured: true,
		status: "Producción",
		detailedStatus: "Estudio activo con sistema de reservas y catálogo completo",
		progress: 100,
		icon: "Sparkle",
		startDate: "2024-03",
		endDate: "2024-05",
		clientType: "Belleza",
		teamSize: 1
	},
	{
		id: 10,
		title: "Micropigmentadora Internacional",
		subtitle: "Certificación Internacional en Micropigmentación",
		description: "Landing page para profesional internacional, promocionando curso certificado en micropigmentación. Incluye información detallada, formulario de inscripción y testimonios.",
		technologies: ["React", "Tailwind CSS", "Vite", "EmailJS"],
		category: "beauty",
		github: "#",
		demo: "#",
		videoSrc: "/videosProjects/landingmicropigmentacion.mp4",
		posterSrc: "https://picsum.photos/800/600?random=10",
		featured: true,
		status: "Producción",
		detailedStatus: "Landing activa para venta de curso internacional",
		progress: 100,
		icon: "Certificate",
		startDate: "2024-04",
		endDate: "2024-06",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 11,
		title: "CafeDoncar",
		subtitle: "Especialistas en Pizzas y Hamburguesas 100% Caseras",
		description: "Web SPA para restaurante con menú online, sistema de armado de pedido y envío directo por WhatsApp. Incluye galería de productos y promociones.",
		technologies: ["React", "Tailwind CSS", "Vite", "WhatsApp API"],
		category: "food",
		github: "#",
		demo: "#",
		videoSrc: "/videosProjects/CafeDoncar.mp4",
		posterSrc: "/posters/posterCafeDoncar.PNG",
		featured: true,
		status: "Producción",
		detailedStatus: "Sistema de pedidos online funcionando",
		progress: 100,
		icon: "Pizza",
		startDate: "2024-05",
		endDate: "2024-07",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 12,
		title: "OZZcycling",
		subtitle: "Bicicletería y Taller Especializado",
		description: "Web institucional para bicicletería premium en Buenos Aires. Presenta servicios de taller, catálogo de productos y centro Shimano Service Center Oficial.",
		technologies: ["React", "Tailwind CSS", "Vite", "EmailJS"],
		category: "retail",
		github: "#",
		demo: "#",
		videoSrc: "#",
		posterSrc: "https://picsum.photos/800/600?random=12",
		featured: true,
		status: "Producción",
		detailedStatus: "Sitio web activo y actualizado",
		progress: 100,
		icon: "Bike",
		startDate: "2024-06",
		endDate: "2024-08",
		clientType: "Retail",
		teamSize: 2
	}
];

export default projects;
