const projects = [
	{
		id: 1,
		title: "Maestra Patagónica",
		subtitle: "Tienda de Recursos Educativos",
		description: "Plataforma e-commerce especializada en recursos educativos para docentes. Incluye sistema de compras, catálogo interactivo y área de usuario.",
		technologies: ["HTML5","React", "Node.js", "MongoDB", "Vite", "Tailwind CSS"],
		category: "ecommerce",
		github: "https://github.com/31pablo05/MaestraPatagonica",
		demo: "https://maestra-patagonica.vercel.app/inicio",
		videoSrc: "/videosProjects/MaestraPatagonica.mp4",
		posterSrc: "/posters/posterMaestraPatagonica.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Proyecto completado y en producción activa",
		progress: 20,
		icon: "GraduationCap",
		startDate: "2024-01",
		endDate: "2024-03",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 2,
		title: "Chacra Agroecológica Pichirayén",
		subtitle: "Sitio web SPA · Información, Galería y Contacto",
		description: "Diseñé un sitio web SPA para la Chacra Agroecológica Pichirayén 🌱, destacando su producción sustentable y experiencias de turismo rural. La plataforma incluye galería de fotos, información sobre actividades y propuestas educativas, así como un sistema de contacto fácil para coordinar visitas y consultas",
		technologies: ["HTML5", "CSS", "Tailwind CSS", "JavaScript", "React", "Vite", "WhatsApp API"],
		category: "wellness",
		github: "https://github.com/31pablo05/PichiRayen",
		demo: "https://pichirayen.vercel.app/",
		videoSrc: "/videosProjects/pichiRayen.mp4",
		posterSrc: "/posters/posterPichiRayen.webp",
		featured: true,
		status: "Producción",
		detailedStatus: "Sitio web activo con todas las funcionalidades",
		progress: 100,
		icon: "Heart",
		startDate: "2024-02",
		endDate: "2024-04",
		clientType: "Bienestar",
		teamSize: 1
	},
	{
		id: 3,
		title: "Pamela Wissberg Nutrición·Web App Profesional",
		subtitle: "Aplicación web·Consultorio de Nutrición",
		description: "Desarrollé la web de Pamela Wissberg, nutricionista especializada en salud integral 🥗. El sitio presenta información clara sobre sus servicios, propuestas alimentarias y enfoque profesional, además de contar con un sistema de contacto simple para facilitar la comunicación con pacientes y potenciales clientes.",
		technologies: ["HTML5", "Css", "React", "Tailwind CSS", "JavaScript", "Vite"],
		category: "health",
		github: "https://github.com/31pablo05/NutricionistaPamelaWeissberg",
		demo: "https://pamelawissbergnutricion.vercel.app/",
		videoSrc: "/videosProjects/WebAppNutricionista.mp4",
		posterSrc: "/posters/posterNutricionista.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Aplicación completa y funcionando",
		progress: 95,
		icon: "Utensils",
		startDate: "2024-01",
		endDate: "2024-02",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 4,
		title: "Web App Prepizzas",
		subtitle: "Sistema de Pedidos de Pizzería",
		description: "Desarrollé una web app para Prepizzas, una pizzería local 🍕, que permite a los clientes armar sus propias pizzas personalizadas eligiendo ingredientes, tamaño y tipo de masa. La aplicación incluye un sistema de pedidos fácil de usar que envía la orden directamente al WhatsApp del negocio para una gestión rápida y eficiente.",
		technologies: ["HTML5","React", "Node.js", "JavaScript", "Render", "Tailwind CSS","vite"],
		category: "food",
		github: "https://github.com/31pablo05/Prepizzas/tree/main",
		demo: "https://prepizzas.vercel.app/",
		videoSrc: "/videosProjects/WebAppPrepizzas.mp4",
		posterSrc: "/posters/posterAppPrepizzas.webp",
		featured: false,
		status: "Producción",
		detailedStatus: "En fase de testing y optimización",
		progress: 100,
		icon: "Utensils",
		startDate: "2024-04",
		endDate: "2024-06",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 5,
		title: "Federico Forquera·Fotografía & Filmmaking",
		subtitle: "Portfolio digital·Fotografía y Video Profesional",
		description: "Diseñé el portfolio digital de Federico Forquera 📸🎬, fotógrafo y filmmaker. El sitio incluye una galería dinámica con animaciones fluidas, efectos visuales modernos y un formulario de contacto optimizado para conectar de forma directa con potenciales clientes.",
		technologies: ["HTML5","CSS","React", "JavaScript", "Vite", "Tailwind CSS", "Framer Motion"],
		category: "portfolio",
		github: "https://github.com/31pablo05/FedeForquera",
		demo: "https://fedeforqueraphotographerfilmmake.vercel.app/",
		videoSrc: "/videosProjects/FedeForquera.mp4",
		posterSrc: "/posters/posterFilmaker.webp",
		featured: true,
		status: "Producción",
		detailedStatus: "Portfolio activo con galería completa",
		progress: 100,
		icon: "Camera",
		startDate: "2024-03",
		endDate: "2024-05",
		clientType: "Creativo",
		teamSize: 1
	},
	{
		id: 6,
		title: "Francisco Torres Osteopatía·Web App Profesional",
		subtitle: "Sitio web SPA·Consultorio de Osteopatía",
		description: "Diseñé la web de Francisco Torres Osteopatía 🧑‍⚕️, un sitio informativo y funcional para su consultorio. Incluye secciones sobre tratamientos, enfoque profesional y un sistema en desarrollo para la gestión de turnos online, con el objetivo de facilitar la atención y el contacto con pacientes.",
		technologies: ["HTML5", "CSS", "React", "Tailwind CSS", "JavaScript", "Vite"],
		category: "health",
		github: "https://github.com/31pablo05/appFranciscoTorres",
		demo: "https://franciscotorres.vercel.app/",
		videoSrc: "/videosProjects/FranciscoTorresOsteopatia.mp4",
		posterSrc: "/posters/posterOsteopatia.webp",
		featured: false,
		status: "Producción",
		detailedStatus: "Implementando sistema de turnos",
		progress: 100,
		icon: "Heart",
		startDate: "2024-05",
		endDate: "2024-07",
		clientType: "Salud",
		teamSize: 1
	},
	{
		id: 7,
		title: "TaDi · Asistente de Escritorio con IA",
		subtitle: "Gestión de tareas · IA · Productividad diaria",
		description: "Desarrollé TaDi, una aplicación de escritorio creada con Electron y conectada a la API de Gemini 🤖. Funciona como asistente personal, ayudándome a organizar el día con gestión de tareas, recordatorios y datos útiles como el clima. Además, integra recomendaciones personalizadas con IA para fomentar nuevos hábitos y mejorar la productividad diaria.",
		technologies: ["Electron", "React", "JavaScript", "Tailwind CSS", "CSS"],
		category: "productivity",
		github: "https://github.com/31pablo05/TaDi",
		demo: "#",
		videoSrc: "#",
		posterSrc: "/posters/TaDi-Captura.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Desarrollando funciones avanzadas",
		progress: 65,
		icon: "Code2",
		startDate: "2024-04",
		endDate: "2024-08",
		clientType: "Productividad",
		teamSize: 1
	},
	{
  id: 8,
  title: "TrueColor · Color Picker de Imágenes",
  subtitle: "Herramienta Web · Diseño & Creatividad",
  description: "Desarrollé TrueColor 🎨, una herramienta online que permite identificar y extraer colores directamente desde imágenes. Incluye selector de color preciso, visualización en tiempo real y copia de códigos HEX/RGB para usarlos en proyectos de diseño, branding o desarrollo web.",
  technologies: ["HTML5", "CSS", "React", "JavaScript", "Vite", "Tailwind CSS"],
  category: "tools",
  github: "https://github.com/31pablo05/truecolor",
  demo: "https://truecolor.vercel.app/",
  videoSrc: "/videosProjects/TrueColor.mp4",
  posterSrc: "/posters/posterTrueColor .webp",
  featured: true,
  status: "Producción",
  detailedStatus: "Herramienta activa y funcional",
  progress: 100,
  icon: "Palette",
  startDate: "2024-06",
  endDate: "2024-07",
  clientType: "Herramienta Creativa",
  teamSize: 1
}
,
	{
		id: 9,
		title: "MYBEAUTYSTUDY · Estudio de Cejas y Pestañas",
		subtitle: "Web SPA·Reservas Online y Catálogo de Servicios",
		description: "Diseñé la plataforma digital de MYBEAUTYSTUDY 💎, un estudio especializado en cejas y pestañas. El sitio presenta un catálogo de servicios atractivo, sistema de reservas online y área de contacto profesional, ofreciendo una experiencia clara y moderna para clientes que buscan agendar tratamientos de belleza.",
		technologies: ["HTML5", "CSS", "React", "JavaScript", "Tailwind CSS", "Vite"],
		category: "beauty",
		github: "https://github.com/31pablo05/MYBeautyStudy",
		demo: "https://mybeautystudy.vercel.app/",
		videoSrc: "/videosProjects/MyBeautyStudy.mp4",
		posterSrc: "/posters/posterMYBEAUTYSTUDY.webp",
		featured: true,
		status: "Producción",
		detailedStatus: "Estudio activo con sistema de reservas y catálogo completo",
		progress: 100,
		icon: "Sparkle",
		startDate: "2025-05",
		endDate: "2025-06",
		clientType: "Belleza",
		teamSize: 1
	},
	{
		id: 10,
		title: "Landing Page · Curso Internacional de Micropigmentación",
		subtitle: "Promoción de curso certificado · Formación profesional",
		description: "Diseñé una landing page promocional para una profesional internacional en micropigmentación 🎓✨. El sitio está orientado a la venta de un curso certificado, con secciones claras sobre el programa, formulario de inscripción integrado y testimonios de alumnos, logrando una experiencia convincente para captar nuevos estudiantes.",
		technologies: ["HTML5", "CSS", "React", "JSX", "JavaScript", "Tailwind CSS", "Vite"],
		category: "beauty",
		github: "https://github.com/31pablo05/-micropicmentadoraInternacional-",
		demo: "https://micropicmentadora-internacional.vercel.app/",
		videoSrc: "/videosProjects/MicropigmentadoraLanding.mp4",
		posterSrc: "/posters/posterMicropigmentadora.webp",
		featured: true,
		status: "Producción",
		detailedStatus: "Landing activa para venta de curso internacional",
		progress: 100,
		icon: "Certificate",
		startDate: "2025-04",
		endDate: "2025-05",
		clientType: "Educativo",
		teamSize: 1
	},
	{
		id: 11,
		title: "Café Doncar–Web de Pedidos Online",
		subtitle: "Especialistas en Pizzas y Hamburguesas 100% Caseras",
		description: "Diseñé una SPA intuitiva para Café Doncar que permite a los clientes explorar el menú, armar pedidos personalizados y enviarlos directamente por WhatsApp. La web incluye galería de productos, promociones y optimización para mejorar la experiencia de compra y aumentar las ventas del restaurante.",
		technologies: ["HTML5", "CSS", "React", "JSX","JavaScript", "Tailwind CSS", "WhatsApp API"],
		category: "food",
		github: "https://github.com/31pablo05/CafeDoncar",
		demo: "https://cafe-doncar.vercel.app/",
		videoSrc: "/videosProjects/CafeDoncar.mp4",
		posterSrc: "/posters/posterCafeDoncar.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Sistema de pedidos online funcionando",
		progress: 85,
		icon: "Pizza",
		startDate: "2025-05",
		endDate: "",
		clientType: "Restaurante",
		teamSize: 2
	},
	{
		id: 12,
		title: "OZZcycling–PWA para Ciclistas",
		subtitle: "Bicicletería Premium y Taller Especializado, accesible desde web y celular",
		description: "Diseñé una Progressive Web App para OZZcycling, combinando web institucional y funcionalidades útiles para ciclistas: catálogo de productos, servicios de taller y centro Shimano Service Center Oficial. Optimizada para cualquier dispositivo, permite a los usuarios explorar, contactar y planificar su experiencia de forma rápida y práctica.",
		technologies: ["HTML5", "CSS", "React", "JSX","JavaScript", "Tailwind CSS", "Vite", "WhatsApp API"],
		category: "retail",
		github: "https://github.com/31pablo05/OZZcycling",
		demo: "https://ozzcycling.vercel.app/",
		videoSrc: "/videosProjects/OZZcycling.mp4",
		posterSrc: "/posters/posterOZZ.webp",
		featured: true,
		status: "Desarrollo",
		detailedStatus: "Sitio web activo y actualizado",
		progress: 75,
		icon: "Bike",
		startDate: "2025-07",
		endDate: "",
		clientType: "Retail",
		teamSize: 2
	},
	{
		id: 13,
title: "Blanquería Kuyen – Tienda Online de Hogar",
subtitle: "Acolchados, Sábanas, Cortinas y Más",
description: "Diseñé la web de Blanquería Kuyen con React Router, permitiendo a los clientes navegar entre diferentes secciones de productos del hogar, como acolchados, sábanas, cortinas de baño, almohadas y mochilas. La web incluye galerías, secciones destacadas y contacto directo, ofreciendo una experiencia intuitiva y atractiva para explorar y conocer el catálogo completo.",
technologies: ["HTML5", "CSS", "React", "JSX","JavaScript", "Tailwind CSS", "Responsive Design"],
category: "ecommerce",
github: "https://github.com/31pablo05/Kuyen",
demo: "https://kuyen.vercel.app/",
videoSrc: "/videosProjects/KuyenWeb.mp4",
posterSrc: "/posters/posterKuyen.webp",
featured: true,
status: "Desarrollo",
detailedStatus: "Catálogo online completo y funcional",
progress: 80,
icon: "Bed",
startDate: "2025-07",
endDate: "",
clientType: "Blanquería",
teamSize: 1

	},
	{
		id: 14,
	title: "Mecánica Lolo – Landing Page",
	subtitle: "Taller Mecánico Integral en Trelew",
	description: "Diseñé una landing page moderna para Mecánica Lolo, un taller mecánico de Trelew especializado en reparación y mantenimiento automotor. La web presenta los principales servicios: mecánica general, electricidad, diagnóstico computarizado y contacto directo por WhatsApp. Está optimizada para captar clientes locales, transmitir confianza y facilitar la comunicación rápida con el taller.",
	technologies: ["HTML5", "CSS", "React", "JSX", "JavaScript", "Tailwind CSS", "WhatsApp API"],
	category: "automotive",
	github: "https://github.com/31pablo05/MecanicaLolo",
	demo: "https://mecanicalolo.vercel.app/",
	videoSrc: "/videosProjects/MecanicaLolo.mp4",
	posterSrc: "/posters/posterMecanicaLolo.webp",
	featured: true,
	status: "Desarrollo",
	detailedStatus: "Landing page funcional con contacto directo",
	progress: 70,
	icon: "Wrench",
	startDate: "2025-06",
	endDate: "",
	clientType: "Taller Mecánico",
	teamSize: 1
	},
	{
		id: 15,
	title: "Identificador de Bulones – Herramienta Web",
	subtitle: "Diferenciación por Métrica, Whitworth y Paso de Hilo",
	description: "Desarrollé una herramienta web especializada para facilitar la identificación de bulones y tornillos en ferreterías y bulonerías. Permite al empleado reconocer rápidamente el diámetro, tipo de rosca (métrica o Whitworth) y distinguir si es paso fino o común. Su objetivo es agilizar la búsqueda del bulón correcto, reducir errores y optimizar la atención al cliente.",
	technologies: ["HTML5", "CSS", "React", "JSX", "JavaScript", "Tailwind CSS"],
	category: "tools",
	github: "https://github.com/31pablo05/HerramientaBuloneria",
	demo: "https://herramienta-buloneria.vercel.app/",
	videoSrc: "/videosProjects/HerramientaBuloneria.mp4",
	posterSrc: "/posters/posterBuloneria.webp",
	featured: true,
	status: "Desarrollo",
	detailedStatus: "Herramienta funcional para identificar bulones",
	progress: 75,
	icon: "Settings",
	startDate: "2025-07",
	endDate: "",
	clientType: "Ferreterías y Bulonerías",
	teamSize: 1
	},
	{
		id: 16,
		title: "Recetas Pasteleras · Astro Demo",
		subtitle: "Web de recetas, ingredientes y tips de pastelería",
		description: "Demostración de una web para mostrar recetas de pastelería, ingredientes, tips y consejos. Ideal para el mundo gastronómico, pastelería, galletitas y repostería. Desarrollada con Astro, Tailwind CSS y TypeScript.",
		technologies: ["Astro", "Tailwind CSS", "TypeScript"],
		category: "gastronomia",
		github: "",
		demo: "https://web-presentacion-recetarios.vercel.app/",
		videoSrc: "",
		posterSrc: "/posters/posterrecetariodemo.webp",
		featured: false,
		status: "Demo",
		detailedStatus: "Proyecto demostrativo para mostrar recetas y tips de pastelería",
		progress: 100,
		icon: "Cookie",
		startDate: "2025-10",
		endDate: "",
		clientType: "Gastronomía / Pastelería",
		teamSize: 1
	},
	{
		id: 17,
		title: "Vivero Patagonia · SPA Demo",
		subtitle: "Web de vivero, servicios, galería y contacto en una sola página",
		description: "Demostración de una web para un vivero, desarrollada con Astro y Tailwind CSS. Es una SPA donde toda la navegación se realiza en la misma página mediante scroll. Incluye inicio, servicios, galería de plantas y contacto con ubicación y horarios. Ideal para mostrar el catálogo y facilitar la comunicación con clientes.",
		technologies: ["Astro", "Tailwind CSS", "TypeScript"],
		category: "vivero",
		github: "https://github.com/31pablo05/vivero/tree/main/Vivero",
		demo: "https://vivero-smoky.vercel.app/",
		videoSrc: "",
		posterSrc: "/posters/posterviverodemo.webp",
		featured: false,
		status: "Demo",
		detailedStatus: "SPA demostrativa para viveros, con navegación y secciones integradas en una sola página.",
		progress: 100,
		icon: "Leaf",
		startDate: "2025-10",
		endDate: "",
		clientType: "Vivero / Jardinería",
		teamSize: 1
	},
	{
		id: 18,
		title: "Tetris Web · PWA",
		subtitle: "Juego Tetris instalable, hecho con React, Tailwind y Vite",
		description: "Juego clásico de Tetris desarrollado como web app con React, Tailwind CSS, Vite y CSS personalizado. Incluye soporte PWA para instalarlo de forma nativa en dispositivos móviles y escritorio. Interfaz moderna, controles táctiles y de teclado, animaciones y sistema de puntaje.",
		technologies: ["React", "Tailwind CSS", "Vite", "CSS"],
		category: "juegos",
		github: "",
		demo: "https://tetris-papa.vercel.app/",
		videoSrc: "",
		posterSrc: "/posters/posterTetris.webp",
		featured: false,
		status: "Demo",
		detailedStatus: "Juego Tetris funcional, instalable como PWA, con controles y animaciones.",
		progress: 60,
		icon: "Gamepad2",
		startDate: "2025-10",
		endDate: "",
		clientType: "Juegos / PWA",
		teamSize: 1
	},
	{
		id: 19,
		title: "Curso de Fotografía · Landing Page",
		subtitle: "Landing para promocionar cursos de fotografía profesional",
		description: "Landing page diseñada para promocionar cursos de fotografía. Incluye información del curso, temario, instructor, testimonios y formulario de inscripción. Optimizada para captar estudiantes interesados en aprender técnicas fotográficas profesionales. Diseño atractivo con galería de trabajos y llamadas a la acción claras.",
		technologies: ["React", "Tailwind CSS", "JavaScript", "CSS"],
		category: "educacion",
		github: "",
		demo: "",
		videoSrc: "",
		posterSrc: "/posters/postercursofotos.webp",
		featured: false,
		status: "Demo",
		detailedStatus: "Landing page demostrativa para promocionar cursos de fotografía",
		progress: 100,
		icon: "Camera",
		startDate: "2025-10",
		endDate: "",
		clientType: "Educación / Fotografía",
		teamSize: 1
	},
	{
		id: 20,
		title: "Curso de Repostería · Landing Page",
		subtitle: "Landing para promocionar cursos de pastelería y repostería",
		description: "Landing page especializada en promocionar cursos de repostería y pastelería. Presenta la oferta educativa, recetas destacadas, perfil del instructor, horarios disponibles y sistema de inscripción. Diseñada para atraer estudiantes apasionados por la repostería y convertir visitantes en alumnos inscritos.",
		technologies: ["React", "Tailwind CSS", "JavaScript", "CSS"],
		category: "educacion",
		github: "",
		demo: "",
		videoSrc: "",
		posterSrc: "/posters/postercursopasteleria.webp",
		featured: false,
		status: "Demo",
		detailedStatus: "Landing page demostrativa para promocionar cursos de repostería",
		progress: 100,
		icon: "ChefHat",
		startDate: "2025-10",
		endDate: "",
		clientType: "Educación / Repostería",
		teamSize: 1
	}
];

export default projects;
